from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',views.index,name='index'),
    path('product/<int:id>',views.detail,name='detail'),
    path('createproduct',views.create_product,name='createproduct'),
    path('orders/', views.orders_list, name='orders_list'),
    path('orders/<int:id>', views.order_detail, name='order_detail'),
    path('editproduct/<int:id>', views.edit_product, name='editproduct'),
    path('deleteproduct/<int:id>', views.delete_product, name='deleteproduct'),
    path('register/',views.register, name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='myapp/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='myapp/logout.html'), name='logout'),
    path('invalid/',views.invalid, name='invalid'),
    path('cart/',views.my_purchases, name='my_purchases'),
    path('add-to-cart/<int:id>/',views.add_to_cart,name='add_to_cart'),
    path('submit-order/', views.submit_order, name='submit_order'),
    path('orders/<int:id>/pay/', views.pay_order, name='pay_order'),
    path('orders/detail/<int:id>/download/',views.download_product,name='download_product'),
    path('downloads/', views.my_downloads, name='my_downloads'),
    path('sales/', views.sales_history, name='sales_history'),
    path('wishlist/add/<int:id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/', views.my_wishlist, name='my_wishlist'),
    path('wishlist/remove/<int:id>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('product/<int:id>/review/',views.add_review,name='add_review'),
    path('profile/', views.profile, name='profile'),
    path('change-password/',views.change_password,name='change_password'),
    path('notifications/',views.notifications,name='notifications'),
    path('notifications/<int:id>/read/',views.mark_notification_read,name='mark_notification_read'),
    path('cart/increase/<int:id>/',views.increase_quantity,name='increase_quantity'),
    path('cart/decrease/<int:id>/',views.decrease_quantity,name='decrease_quantity'),
    path('cart/remove/<int:id>/',views.remove_from_cart,name='remove_from_cart'),
    path('review/<int:id>/edit/',views.edit_review,name='edit_review'),
    path('review/<int:id>/delete/',views.delete_review,name='delete_review'),
    path('notifications/read-all/',views.mark_all_notifications_read,name='mark_all_notifications_read'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='myapp/password_reset.html',email_template_name='myapp/password_reset_email.html',subject_template_name='myapp/password_reset_subject.txt',success_url='/password-reset/done/'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='myapp/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='myapp/password_reset_confirm.html',success_url='/reset/done/'),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='myapp/password_reset_complete.html'),name='password_reset_complete'),
]
