# Generated by Django 6.1 on 2026-08-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='stripe_payment_id',
        ),
    ]
